# Generated by Django 3.1.7 on 2021-03-22 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dynamic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(blank=True, max_length=500, null=True)),
                ('view_response', models.BooleanField(default=True)),
                ('user_response', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DynamicQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques', models.CharField(blank=True, max_length=500, null=True)),
                ('form', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='survey.dynamic')),
            ],
        ),
        migrations.CreateModel(
            name='MyGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myimage', models.ImageField(blank=True, default='dd.png', null=True, upload_to='img/%y')),
                ('heading', models.CharField(blank=True, max_length=500, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('question', models.TextField(null=True)),
                ('view_response', models.BooleanField(default=True)),
                ('user_response', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('question', models.TextField(null=True)),
                ('view_response', models.BooleanField(default=True)),
                ('user_response', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res', models.TextField()),
                ('ques', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.question')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='POptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(blank=True, max_length=500, null=True)),
                ('option_count', models.IntegerField(default=0, null=True)),
                ('ques', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='survey.pquestion')),
            ],
        ),
        migrations.CreateModel(
            name='DynamicResponses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res', models.CharField(blank=True, max_length=500, null=True)),
                ('form', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='survey.dynamicquestion')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=13, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True)),
                ('dob', models.DateField(default=django.utils.timezone.now, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('user_image', models.ImageField(blank=True, default='no-user.jpg', null=True, upload_to='img/%y')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
