# Generated by Django 3.1.7 on 2021-03-22 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicquestion',
            name='field_type',
            field=models.CharField(choices=[('T', 'text'), ('S', 'select'), ('R', 'radio')], default='T', max_length=1, null=True),
        ),
    ]
